### ISSUE TITLE
feat: Implement `hasAccess()` tests

### ISSUE THREAD

**Issue by cromatikap** [cromatikap/gated-content-nft-access#2]
Implement the following tests for [`hasAccess() function`](https://github.com/cromatikap/gated-content-nft-access/blob/3a6a87daf136712433742077cbfef4982711d7cb/contracts/erc4908/ERC4908.sol#L79C14-L79C23):
- [Should have access](https://github.com/cromatikap/gated-content-nft-access/blob/c9c47134c8ae130e0406d7e3e7ed82940f7e445a/test/ERC4908Example.ts#L165)
- [Should not have access](https://github.com/cromatikap/gated-content-nft-access/blob/c9c47134c8ae130e0406d7e3e7ed82940f7e445a/test/ERC4908Example.ts#L176)

**Comment by BChainbuddy** [comment]
I would love to work on this issue!

**Comment by cromatikap** [comment]
Sure! Go ahead, thanks!
