### ISSUE TITLE
add expiration time check in `hasAccess()`

### ISSUE THREAD

**Issue by cromatikap** [cromatikap/gated-content-nft-access#7]
# Abstract

NFTs have an expiration time contained in the [`struct Metadata`](https://github.com/cromatikap/gated-content-nft-access/blob/92b054779fe505def5865697c194a026bce6e79a/contracts/erc4908/ERC4908.sol#L20).

# Description

Modify `hasAccess()` to return a tuple `(bool, string)` where the value can take:
- (false, "access doesn't exist") <- You can reuse [`existAccess()`](https://github.com/cromatikap/gated-content-nft-access/blob/92b054779fe505def5865697c194a026bce6e79a/contracts/erc4908/ERC4908.sol#L55)
- (false, "access is expired") <- compare `expirationTime` and `block.timestamp`
- (true, "access granted")

The tests will need to be modified accordingly

**Comment by BChainbuddy** [comment]
I would love to do this one as well!

**Comment by cromatikap** [comment]
💯 awesome! Thank you very much!

**Comment by cromatikap** [comment]
Solved by #8 🥇
